#!/usr/bin/env bash
export GPUQ_QUEUE_ROOT=/var/lib/gpuq/queue/
export GPUQ_SIGNALS_ROOT=/var/lib/gpuq/signals/
export PYTHONPATH=/opt/gpuq:$PYTHONPATH
exec /opt/gpuq/venv/bin/python -m gpuq_cli.gpuq "$@"